<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsRoslynComponent>true</IsRoslynComponent>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<IncludeSymbols>false</IncludeSymbols>
		<NoWarn>$(NoWarn);NU5128</NoWarn>

		<Description>A Roslyn source generator that emits strongly-typed localisation accessors from XLIFF 2.0 and 2.1 documents for the Lumoin.Vericula toolkit.</Description>

		<DevelopmentDependency>true</DevelopmentDependency>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
		<PackageReference Include="System.Memory" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Bcl.HashCode" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

</Project>
