using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Text;

namespace Lumoin.Vericula.SourceGenerators.Tests;

[TestClass]
public sealed class XliffSourceGeneratorTests
{
    public TestContext TestContext { get; set; } = null!;

    private static string TwoLanguageXliff => """
        <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="fi">
          <file id="wallet">
            <unit id="HomeHeadline">
              <segment>
                <source>Your credentials, on your terms.</source>
                <target>Omat todisteesi, omin ehdoin.</target>
              </segment>
            </unit>
            <unit id="HomeIntro">
              <segment>
                <source>The wallet stores the claims you hold.</source>
              </segment>
            </unit>
          </file>
        </xliff>
        """;

    private static string TwoLanguageXliffWithAnIrrelevantComment => """
        <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="fi">
          <!-- refreshed -->
          <file id="wallet">
            <unit id="HomeHeadline">
              <segment>
                <source>Your credentials, on your terms.</source>
                <target>Omat todisteesi, omin ehdoin.</target>
              </segment>
            </unit>
            <unit id="HomeIntro">
              <segment>
                <source>The wallet stores the claims you hold.</source>
              </segment>
            </unit>
          </file>
        </xliff>
        """;

    private static string InvalidUnitIdXliff => """
        <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
          <file id="wallet">
            <unit id="Not a valid identifier">
              <segment>
                <source>Some text.</source>
              </segment>
            </unit>
            <unit id="ValidId">
              <segment>
                <source>Other text.</source>
              </segment>
            </unit>
          </file>
        </xliff>
        """;

    private static string DoctypeXliff => """
        <?xml version="1.0"?>
        <!DOCTYPE xliff [<!ENTITY x "y">]>
        <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
          <file id="wallet">
            <unit id="ValidId">
              <segment>
                <source>Some text.</source>
              </segment>
            </unit>
          </file>
        </xliff>
        """;

    private static string TwoLanguageGoldenSource => """
            // <auto-generated/>
            //Generated by Lumoin.Vericula.SourceGenerators from the project's .xliff additional files.

            namespace Bootstrap.Localization
            {
                /// <summary>
                /// Strongly typed access to the translations carried by the project's XLIFF documents.
                /// <see cref="Resolve"/> tries the exact current UI culture, then each of its parent
                /// cultures in turn, then the culture's neutral primary subtag, then the source
                /// language, and finally returns the key itself.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Lumoin.Vericula.SourceGenerators", "1.0.0")]
                public static class Translations
                {
                    private static readonly global::System.Collections.Generic.Dictionary<string, string> LanguageEn = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)
                    {
                        ["HomeHeadline"] = "Your credentials, on your terms.",
                        ["HomeIntro"] = "The wallet stores the claims you hold.",
                    };

                    private static readonly global::System.Collections.Generic.Dictionary<string, string> LanguageFi = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)
                    {
                        ["HomeHeadline"] = "Omat todisteesi, omin ehdoin.",
                    };

                    private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, string>> Languages = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, string>>(global::System.StringComparer.OrdinalIgnoreCase)
                    {
                        ["en"] = LanguageEn,
                        ["fi"] = LanguageFi,
                    };

                    /// <summary>
                    /// Resolves the translation for the given unit id: the current UI culture, then its
                    /// parent cultures, then the neutral primary-subtag table, then the source language,
                    /// and finally the id itself.
                    /// </summary>
                    public static string Resolve(string key)
                    {
                        global::System.Globalization.CultureInfo culture = global::System.Globalization.CultureInfo.CurrentUICulture;
                        while(culture != null && !global::System.String.IsNullOrEmpty(culture.Name))
                        {
                            global::System.Collections.Generic.Dictionary<string, string> table;
                            string value;
                            if(Languages.TryGetValue(culture.Name, out table) && table.TryGetValue(key, out value))
                            {
                                return value;
                            }

                            culture = culture.Parent;
                        }

                        string neutral = global::System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                        global::System.Collections.Generic.Dictionary<string, string> neutralTable;
                        string neutralValue;
                        if(Languages.TryGetValue(neutral, out neutralTable) && neutralTable.TryGetValue(key, out neutralValue))
                        {
                            return neutralValue;
                        }

                        string fallback;
                        return LanguageEn.TryGetValue(key, out fallback) ? fallback : key;
                    }

                    /// <summary>
                    /// Gets the translation of "Your credentials, on your terms.".
                    /// </summary>
                    public static string HomeHeadline => Resolve("HomeHeadline");

                    /// <summary>
                    /// Gets the translation of "The wallet stores the claims you hold.".
                    /// </summary>
                    public static string HomeIntro => Resolve("HomeIntro");
                }
            }

            """;

    private static string InvalidUnitIdGoldenSource => """
            // <auto-generated/>
            //Generated by Lumoin.Vericula.SourceGenerators from the project's .xliff additional files.

            namespace Bootstrap.Localization
            {
                /// <summary>
                /// Strongly typed access to the translations carried by the project's XLIFF documents.
                /// <see cref="Resolve"/> tries the exact current UI culture, then each of its parent
                /// cultures in turn, then the culture's neutral primary subtag, then the source
                /// language, and finally returns the key itself.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Lumoin.Vericula.SourceGenerators", "1.0.0")]
                public static class Translations
                {
                    private static readonly global::System.Collections.Generic.Dictionary<string, string> LanguageEn = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)
                    {
                        ["ValidId"] = "Other text.",
                    };

                    private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, string>> Languages = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, string>>(global::System.StringComparer.OrdinalIgnoreCase)
                    {
                        ["en"] = LanguageEn,
                    };

                    /// <summary>
                    /// Resolves the translation for the given unit id: the current UI culture, then its
                    /// parent cultures, then the neutral primary-subtag table, then the source language,
                    /// and finally the id itself.
                    /// </summary>
                    public static string Resolve(string key)
                    {
                        global::System.Globalization.CultureInfo culture = global::System.Globalization.CultureInfo.CurrentUICulture;
                        while(culture != null && !global::System.String.IsNullOrEmpty(culture.Name))
                        {
                            global::System.Collections.Generic.Dictionary<string, string> table;
                            string value;
                            if(Languages.TryGetValue(culture.Name, out table) && table.TryGetValue(key, out value))
                            {
                                return value;
                            }

                            culture = culture.Parent;
                        }

                        string neutral = global::System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                        global::System.Collections.Generic.Dictionary<string, string> neutralTable;
                        string neutralValue;
                        if(Languages.TryGetValue(neutral, out neutralTable) && neutralTable.TryGetValue(key, out neutralValue))
                        {
                            return neutralValue;
                        }

                        string fallback;
                        return LanguageEn.TryGetValue(key, out fallback) ? fallback : key;
                    }

                    /// <summary>
                    /// Gets the translation of "Other text.".
                    /// </summary>
                    public static string ValidId => Resolve("ValidId");
                }
            }

            """;

    [TestMethod]
    public void TheGeneratedSourceForTwoLanguagesMatchesTheGoldenOutput()
    {
        //Kills any mutant that changes BuildAccessorSource's formatting, dictionary
        //ordering, field naming or doc-comment text: an exact comparison notices any
        //byte that a substring check would have missed.
        var result = RunGenerator(TwoLanguageXliff, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(0, result.Diagnostics);
        var generated = result.Results[0].GeneratedSources;
        Assert.HasCount(1, generated);
        Assert.AreEqual(Normalize(TwoLanguageGoldenSource), Normalize(generated[0].SourceText.ToString()));
    }

    [TestMethod]
    public void TheGeneratedSourceWhenAUnitIdIsInvalidMatchesTheGoldenOutputAndReportsAnExactDiagnostic()
    {
        //Kills a mutant that changes the VFX301 id, severity or message text, and any
        //mutant that changes which units survive an invalid sibling id.
        var result = RunGenerator(InvalidUnitIdXliff, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Diagnostic diagnostic = result.Diagnostics[0];
        Assert.AreEqual(WellKnownGeneratorDiagnostics.InvalidUnitId, diagnostic.Id);
        Assert.AreEqual(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.AreEqual(
            "The unit id 'Not a valid identifier' in 'wallet.fi.xliff' is not a valid C# identifier, so no accessor was generated for it",
            diagnostic.GetMessage(CultureInfo.InvariantCulture));

        var generated = result.Results[0].GeneratedSources;
        Assert.HasCount(1, generated);
        Assert.AreEqual(Normalize(InvalidUnitIdGoldenSource), Normalize(generated[0].SourceText.ToString()));
    }

    [TestMethod]
    public void AMalformedXliffDocumentIsRefusedWithAnExactParseFailureDiagnostic()
    {
        var result = RunGenerator("<xliff version=\"2.0\" srcLang=\"en\"", "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Diagnostic diagnostic = result.Diagnostics[0];
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, diagnostic.Id);
        Assert.AreEqual(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.AreEqual(
            "The XLIFF file 'wallet.fi.xliff' could not be parsed: Unexpected end of file has occurred. The following elements are not closed:  Line 1, position 34.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture));
        Assert.HasCount(0, result.Results[0].GeneratedSources);
    }

    [TestMethod]
    public void ADocumentDeclaringADoctypeIsRefusedWithAParseFailureDiagnostic()
    {
        //Kills a mutant that drops DtdProcessing.Prohibit (or the XmlResolver: null) from
        //the reader settings: without it, a DOCTYPE with an external or internal entity
        //would be parsed instead of refused, and this diagnostic would never be reported.
        var result = RunGenerator(DoctypeXliff, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Diagnostic diagnostic = result.Diagnostics[0];
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, diagnostic.Id);
        Assert.AreEqual(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.HasCount(0, result.Results[0].GeneratedSources);
    }

    [TestMethod]
    public void TheFinnishAccessorReturnsTheFinnishTargetUnderFinnishCulture()
    {
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(
            TwoLanguageXliff, "ExecutionFinnish", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("fi");

            Assert.AreEqual("Omat todisteesi, omin ehdoin.", GetAccessor(translationsType, "HomeHeadline"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void TheEnglishAccessorReturnsTheSourceTextUnderEnglishCulture()
    {
        //Kills a mutant that swaps Resolve's language lookup for the wrong table: under
        //"en", the resolved value must be the English table's own text, not the Finnish one.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(
            TwoLanguageXliff, "ExecutionEnglish", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("en");

            Assert.AreEqual("Your credentials, on your terms.", GetAccessor(translationsType, "HomeHeadline"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void TheAccessorFallsBackToTheSourceTextUnderACultureWithNoTranslationTable()
    {
        //Kills a mutant that drops Resolve's fallback to the source-language table (for
        //example replacing it with "return key;"): under "sv", for which no table exists,
        //the only way to see the English source text is to have taken that fallback.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(
            TwoLanguageXliff, "ExecutionSwedish", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("sv");

            Assert.AreEqual("Your credentials, on your terms.", GetAccessor(translationsType, "HomeHeadline"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void TheAccessorFallsBackToTheSourceTextWhenTheUnitHasNoTarget()
    {
        //Kills the same source-language-fallback mutant from a different angle: HomeIntro
        //has no Finnish target at all, so under "fi" the fallback is the only path that
        //returns text instead of throwing or returning the bare key.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(
            TwoLanguageXliff, "ExecutionMissingTarget", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("fi");

            Assert.AreEqual("The wallet stores the claims you hold.", GetAccessor(translationsType, "HomeIntro"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void TheParsedDocumentAndCollectedModelStepsStayCachedAcrossAnUnrelatedChange()
    {
        //Kills a mutant that reverts XliffDocumentModel.Units from EquatableArray<UnitModel>
        //back to ImmutableArray<UnitModel>: ImmutableArray's own equality compares the
        //wrapped array by reference, so a genuinely re-parsed but content-equal document
        //would then report Modified instead of Unchanged, and this assertion would fail.
        var generator = new XliffSourceGenerator();
        var originalText = new MemoryAdditionalText("wallet.fi.xliff", TwoLanguageXliff);
        var driverOptions = new GeneratorDriverOptions(IncrementalGeneratorOutputKind.None, trackIncrementalGeneratorSteps: true);
        var driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: [originalText],
            parseOptions: null,
            optionsProvider: null,
            driverOptions: driverOptions);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Cacheability",
            syntaxTrees: [],
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);

        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.CancellationToken);

        //The same file, cosmetically re-supplied: a fresh AdditionalText instance whose only
        //textual difference from the original is a comment the parser ignores, so the parsed
        //model must compare equal to the previous run's model for the cache to stay hot. An
        //unrelated syntax tree is added to the compilation too, so nothing about this change
        //is specific to the XLIFF file's own content.
        var refreshedText = new MemoryAdditionalText("wallet.fi.xliff", TwoLanguageXliffWithAnIrrelevantComment);
        driver = (CSharpGeneratorDriver)driver.ReplaceAdditionalText(originalText, refreshedText);
        var nextCompilation = compilation.AddSyntaxTrees(
            CSharpSyntaxTree.ParseText("internal sealed class UnrelatedType { }", cancellationToken: TestContext.CancellationToken));
        driver = (CSharpGeneratorDriver)driver.RunGenerators(nextCompilation, TestContext.CancellationToken);

        ImmutableDictionary<string, ImmutableArray<IncrementalGeneratorRunStep>> trackedSteps =
            driver.GetRunResult().Results[0].TrackedSteps;
        AssertCachedOrUnchanged(trackedSteps, WellKnownGeneratorSteps.ParsedDocument);
        AssertCachedOrUnchanged(trackedSteps, WellKnownGeneratorSteps.CollectedModel);
    }

    [TestMethod]
    public void ALineBreakInSourceTextIsStrippedFromTheDocCommentAndKeptVerbatimInTheStringLiteral()
    {
        //r1-93: a CRLF, a LINE SEPARATOR (U+2028), a doc-comment close, a triple slash, a
        //quote and a brace inside <source> used to spill out of the single-line ///
        //summary and become code; if that regressed, either the generated file would fail
        //to compile (asserted by EmitAndLoad below) or the returned text would not be the
        //original, unbroken string, because the string literal is unaffected but a
        //surviving line break would have split the source into two statements.
        string xliff = """
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Injection">
                  <segment>
                    <source>Line one&#13;&#10;Line two&#8232;Line three */ /// "quoted" { braces }</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """;
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(xliff, "SecurityInjection", TestContext.CancellationToken);
        try
        {
            string expected = "Line one\r\nLine two\u2028Line three */ /// \"quoted\" { braces }";

            Assert.AreEqual(expected, GetAccessor(translationsType, "Injection"));
        }
        finally
        {
            context.Unload();
        }
    }

    [TestMethod]
    public void AUnitIdThatIsAKeywordGetsAVerbatimIdentifierAccessor()
    {
        //r1-47: "class" passes SyntaxFacts.IsValidIdentifier but is a reserved keyword; the
        //fix escapes it as @class instead of skipping it. Without the escape, the emitted
        //`public static string class => ...;` would fail to compile, and EmitAndLoad would
        //fail the assertion below instead of finding the property under its escaped name.
        string xliff = """
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="class">
                  <segment>
                    <source>Reserved word text.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """;
        var result = RunGenerator(xliff, "Keyword", TestContext.CancellationToken);

        Assert.HasCount(0, result.Diagnostics);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("public static string @class => Resolve(\"class\");", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void AUnitIdThatCollidesWithAGeneratedMemberIsSkippedWithADiagnostic()
    {
        //r1-47: "Resolve" is a valid identifier and not a keyword, but the generated class
        //already declares a member by that name; without the reserved-name check the
        //generator would emit a second `Resolve` member (CS0102) instead of reporting
        //VFX301 and skipping the accessor.
        string xliff = """
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Resolve">
                  <segment>
                    <source>Colliding text.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """;
        var result = RunGenerator(xliff, "Collision", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.InvalidUnitId, result.Diagnostics[0].Id);
        Assert.Contains("collides with a member the generated class already declares", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.DoesNotContain("\"Colliding text.\"", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void AHyphenatedAssemblyNameIsSanitizedIntoTheNamespaceWithAWarning()
    {
        //r1-48: an assembly named "my-app" (a common `dotnet new classlib -n my-app`
        //shape) would emit `namespace my-app.Localization`, which fails to parse; the
        //fix sanitizes each namespace segment and reports VFX302 when it had to.
        var result = RunGenerator(TwoLanguageXliff, "my-app", TestContext.CancellationToken);

        Diagnostic? warning = result.Diagnostics.FirstOrDefault(diagnostic => diagnostic.Id == WellKnownGeneratorDiagnostics.InvalidNamespaceSegment);
        Assert.IsNotNull(warning);
        Assert.AreEqual(DiagnosticSeverity.Warning, warning.Severity);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("namespace my_app.Localization", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void AMalformedSourceLanguageTagIsRefusedRatherThanAcceptedVerbatim()
    {
        //r1-48: srcLang="en us" is not a BCP 47 tag (a space is not a valid subtag
        //separator); without validation this string would flow straight into a table key
        //and a field name, silently corrupting both.
        var result = RunGenerator("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en us">
              <file id="wallet">
                <unit id="A">
                  <segment>
                    <source>Text.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, result.Diagnostics[0].Id);
        Assert.Contains("srcLang 'en us' is not a valid BCP 47 language tag", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        Assert.HasCount(0, result.Results[0].GeneratedSources);
    }

    [TestMethod]
    public void PortugueseBrazilAndPortugalKeepSeparateTranslationTables()
    {
        //r1-49: keying by the primary subtag alone ("pt") would let pt-PT overwrite
        //pt-BR (or the reverse, depending on provider order); keying by the full tag
        //keeps LanguagePtBR and LanguagePtPT distinct, and each culture resolves its own.
        var files = new[]
        {
            ("wallet.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
                  <file id="wallet">
                    <unit id="Color">
                      <segment>
                        <source>Color</source>
                      </segment>
                    </unit>
                  </file>
                </xliff>
                """),
            ("wallet.pt-BR.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="pt-BR">
                  <file id="wallet">
                    <unit id="Color">
                      <segment>
                        <source>Color</source>
                        <target>Cor (BR)</target>
                      </segment>
                    </unit>
                  </file>
                </xliff>
                """),
            ("wallet.pt-PT.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="pt-PT">
                  <file id="wallet">
                    <unit id="Color">
                      <segment>
                        <source>Color</source>
                        <target>Cor (PT)</target>
                      </segment>
                    </unit>
                  </file>
                </xliff>
                """)
        };

        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(files, "PtBrPt", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("pt-BR");
            Assert.AreEqual("Cor (BR)", GetAccessor(translationsType, "Color"));

            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("pt-PT");
            Assert.AreEqual("Cor (PT)", GetAccessor(translationsType, "Color"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void ARegionSpecificCultureFallsBackThroughItsParentToAScriptLevelTable()
    {
        //r1-49: Resolve must walk CurrentUICulture.Parent, not stop at the exact tag and
        //the culture's two-letter neutral name; "zh-Hans-CN" has no table of its own and
        //its TwoLetterISOLanguageName is "zh" (for which there is also no table here), but
        //its .NET parent chain passes through "zh-Hans", which does have one. A mutant
        //that deleted the parent walk (leaving only the exact and two-letter checks) would
        //fall through to the English source and fail this assertion.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad(
            [
                ("wallet.zh-Hans.xliff", """
                    <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="zh-Hans">
                      <file id="wallet">
                        <unit id="Color">
                          <segment>
                            <source>Color</source>
                            <target>Color (Hans)</target>
                          </segment>
                        </unit>
                      </file>
                    </xliff>
                    """)
            ],
            "ZhHansParentWalk", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("zh-Hans-CN");

            Assert.AreEqual("Color (Hans)", GetAccessor(translationsType, "Color"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void AStandalonePlaceholderInSourceIsRefusedInsteadOfFlattened()
    {
        //r1-50: XElement.Value on a <source> containing <ph id="1"/> used to silently drop
        //the placeholder and emit "Hello !"; the fix refuses the whole document instead of
        //emitting text with the code silently missing.
        var result = RunGenerator("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Greeting">
                  <segment>
                    <source>Hello <ph id="1" disp="{0}"/>!</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, result.Diagnostics[0].Id);
        Assert.Contains("Inline markup <ph> in unit 'Greeting' is not supported", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        Assert.HasCount(0, result.Results[0].GeneratedSources);
    }

    [TestMethod]
    public void AMarkerAnnotationInSourceIsRefusedInsteadOfFlattened()
    {
        //r1-50: <mrk translate="no"> wraps text, so XElement.Value alone does not notice
        //anything is wrong; without checking descendants for Marker too, "Keep ACME as
        //is" would be emitted with the translate="no" protection silently gone.
        var result = RunGenerator("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Brand">
                  <segment>
                    <source>Keep <mrk id="m1" translate="no">ACME</mrk> as is</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, result.Diagnostics[0].Id);
        Assert.Contains("Inline markup <mrk>", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
    }

    [TestMethod]
    public void AnEmptyTargetFallsBackToTheSourceRatherThanEmittingAnEmptyString()
    {
        //r1-51: <target/> with no text is the usual CAT-tool placeholder for "not yet
        //translated"; without the fallback the fi table would carry an empty string,
        //and this accessor would return "" instead of the English source under "fi".
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="fi">
              <file id="wallet">
                <unit id="Untranslated">
                  <segment state="initial">
                    <source>Hello</source>
                    <target/>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "EmptyTarget", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("fi");

            Assert.AreEqual("Hello", GetAccessor(translationsType, "Untranslated"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void APartiallyTranslatedUnitFallsBackToTheSourceForEveryTranslatedSegment()
    {
        //r1-51: a unit with two segments where only the first has a target used to emit
        //"Hei. " (source-language "World." silently missing) as if it were the complete
        //Finnish text; the fix requires every segment to have a target before any of the
        //unit's text counts as translated.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="fi">
              <file id="wallet">
                <unit id="Partial">
                  <segment>
                    <source>Hello. </source>
                    <target>Hei. </target>
                  </segment>
                  <segment>
                    <source>World.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "PartialTranslation", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("fi");

            Assert.AreEqual("Hello. World.", GetAccessor(translationsType, "Partial"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void ASegmentNeedingTranslationFallsBackEvenWithATarget()
    {
        //r1-51: state="initial" subState="vericula:needsTranslation" is Vericula's own
        //marker that a Modifier copied source into target as a starting point, not a real
        //translation; without checking it, the copied-through text would be presented as
        //a finished Finnish translation instead of falling back to the source.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="fi">
              <file id="wallet">
                <unit id="NeedsWork">
                  <segment state="initial" subState="vericula:needsTranslation">
                    <source>Hello</source>
                    <target>Hello (draft copy)</target>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "NeedsTranslation", TestContext.CancellationToken);
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("fi");

            Assert.AreEqual("Hello", GetAccessor(translationsType, "NeedsWork"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
            context.Unload();
        }
    }

    [TestMethod]
    public void TheSourceTableFieldExistsEvenWhenEveryUnitIdInTheFirstDocumentIsInvalid()
    {
        //r1-52: when the first document (by sort order) contributes no valid unit,
        //Resolve's fallback still names the source-language field; without registering
        //the table up front the generated code would reference a field that was never
        //declared and fail to compile with CS0103, which the assertion below would catch.
        (Type translationsType, AssemblyLoadContext context) = EmitAndLoad("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="1">
                  <segment>
                    <source>Numeric id text.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "OnlyInvalidIds", TestContext.CancellationToken, expectedDiagnosticCount: 1);
        try
        {
            Assert.IsNotNull(translationsType.GetMethod("Resolve", BindingFlags.Public | BindingFlags.Static));
        }
        finally
        {
            context.Unload();
        }
    }

    [TestMethod]
    public void AUnitIdRepeatingAcrossFilesWithDifferentTextReportsADiagnosticAndKeepsTheFirst()
    {
        //r1-53: a unit id repeating across <file> elements with different text is legal
        //XLIFF (ids are unique per file, not per document); without a diagnostic, the
        //second file's text would silently overwrite the first's with no trace.
        var files = new[]
        {
            ("a.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
                  <file id="a">
                    <unit id="Title">
                      <segment>
                        <source>Title of A</source>
                      </segment>
                    </unit>
                  </file>
                </xliff>
                """),
            ("b.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
                  <file id="b">
                    <unit id="Title">
                      <segment>
                        <source>Title of B</source>
                      </segment>
                    </unit>
                  </file>
                </xliff>
                """)
        };

        var result = RunGenerator(files, "DuplicateAcrossFiles", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.InvalidUnitId, result.Diagnostics[0].Id);
        Assert.Contains("was already generated from", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("\"Title of A\"", code, StringComparison.Ordinal);
        Assert.DoesNotContain("\"Title of B\"", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void LanguageTagsThatSplitIntoDifferentSubtagCountsKeepDistinctFieldNamesAndCompile()
    {
        //p1-7: LanguageFieldName used to concatenate subtags with no separator, so "en-ab" ("en" + "ab")
        //and "en-a-b" ("en" + "a" + "b") both built the field name "LanguageEnab" and collided; the
        //generated class then failed to compile with CS0102 for the duplicate field, even though both
        //tags are individually well-formed per LanguageTagPattern. The '_' separator keeps them apart.
        var files = new[]
        {
            ("wallet.a.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="en-ab">
                  <file id="wallet"><unit id="A"><segment><source>Home</source><target>Home-ab</target></segment></unit></file>
                </xliff>
                """),
            ("wallet.b.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="en-a-b">
                  <file id="wallet"><unit id="A"><segment><source>Home</source><target>Home-a-b</target></segment></unit></file>
                </xliff>
                """)
        };

        GeneratorDriverRunResult result = RunGenerator(files, "Subtags", TestContext.CancellationToken);

        Assert.HasCount(0, result.Diagnostics);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("LanguageEn_ab", code, StringComparison.Ordinal);
        Assert.Contains("LanguageEn_a_b", code, StringComparison.Ordinal);
        Assert.IsTrue(SyntaxFacts.IsValidIdentifier("LanguageEn_ab"));
        Assert.IsTrue(SyntaxFacts.IsValidIdentifier("LanguageEn_a_b"));

        //Compiles the generated class for real: without the separator this fails with CS0102, a
        //duplicate-field compiler error the generator itself never reports a diagnostic for.
        (_, AssemblyLoadContext context) = EmitAndLoad(files, "Subtags", TestContext.CancellationToken);
        context.Unload();
    }

    [TestMethod]
    public void IgnorableContentFoldsIntoTheUnitsWholeText()
    {
        //r1-54: an <ignorable> between two segments (leading/trailing whitespace an
        //extractor pulled out) is part of the unit's text per the XLIFF content model;
        //dropping it, as folding only <segment> children did, would yield "Helloworld"
        //instead of the space-preserving "Hello world" asserted below.
        var result = RunGenerator("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Greeting">
                  <segment>
                    <source>Hello</source>
                  </segment>
                  <ignorable>
                    <source> </source>
                  </ignorable>
                  <segment>
                    <source>world</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(0, result.Diagnostics);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("\"Hello world\"", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void AnEmbeddedLineTerminatorInTheSourceTextBecomesASpaceInTheGeneratedDocComment()
    {
        //p1-9: EscapeXmlDocumentation used to just drop each line-terminator character instead of
        //replacing it with a space, so a <source> spanning two lines emitted the doc-comment line
        //`/// Gets the translation of "HelloWorld".`, silently merging the two words together.
        string xliff = """
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Greeting"><segment><source>Hello{NL}World</source></segment></unit>
              </file>
            </xliff>
            """.Replace("{NL}", "\n", StringComparison.Ordinal);

        var result = RunGenerator(xliff, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(0, result.Diagnostics);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("Gets the translation of \"Hello World\".", code, StringComparison.Ordinal);
        Assert.DoesNotContain("HelloWorld", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void AParseFailureDiagnosticCarriesTheDocumentsLineAndColumnWhenAvailable()
    {
        //r1-55: the reader's LoadOptions.SetLineInfo means a failing document's root
        //element carries a real position; without wiring that into the Location the
        //diagnostic reports, this assertion would see Location.None instead of a real
        //external-file span naming the source file and its first line.
        var result = RunGenerator("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0">
              <file id="wallet">
                <unit id="A">
                  <segment>
                    <source>Text.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Location location = result.Diagnostics[0].Location;
        Assert.AreNotEqual(Location.None, location);
        Assert.AreEqual("wallet.fi.xliff", location.GetLineSpan().Path);
        Assert.AreEqual(0, location.GetLineSpan().StartLinePosition.Line);

        //f-20: the method's own name promises the column too, but nothing here asserted it, so a
        //mutant confined to the column computation (LocationOf's Math.Max(0, column - 1), or
        //LineInfoOf's info.LinePosition) survived. The raw string literal's dedent leaves the root
        //<xliff> element starting in column 1 of line 1 with no leading whitespace, so XmlReader's
        //IXmlLineInfo reports LinePosition 2 (1-based, at the 'x' of the element name); LocationOf
        //turns that into the 0-based column 1 asserted here.
        Assert.AreEqual(1, location.GetLineSpan().StartLinePosition.Character);
    }

    [TestMethod]
    public void TargetsWithoutADeclaredTargetLanguageAreRefusedRatherThanDropped()
    {
        //r1-56: a document with <target> content but no trgLang is not valid XLIFF; the
        //generator used to accept it and silently drop every target, so every accessor
        //quietly returned the source text with no warning that translations existed but
        //were unusable.
        var result = RunGenerator("""
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="Greeting">
                  <segment>
                    <source>Hello</source>
                    <target>Hei</target>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, result.Diagnostics[0].Id);
        Assert.Contains("declares <target> elements but", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        Assert.HasCount(0, result.Results[0].GeneratedSources);
    }

    [TestMethod]
    public void LanguageTagFileNameMismatchWarningCarriesTheDocumentsRootLocation()
    {
        //f-16: DocumentLocation returns Location.None for a successfully parsed document, since
        //ParseDocument deliberately keeps Line/Column at 0 on success (to avoid invalidating the
        //incremental cache on edits unrelated to the root element); routing this warning through
        //that same helper meant it could never be anchored to a file at all. DocumentRootLocation
        //falls back to the document's own path at line 1, column 1 instead.
        var files = new[]
        {
            ("wallet.de.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en" trgLang="fr">
                  <file id="wallet"><unit id="A"><segment><source>Home</source><target>Accueil</target></segment></unit></file>
                </xliff>
                """)
        };

        GeneratorDriverRunResult result = RunGenerator(files, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Diagnostic diagnostic = result.Diagnostics[0];
        Assert.AreEqual(WellKnownGeneratorDiagnostics.LanguageTagFileNameMismatch, diagnostic.Id);
        Location location = diagnostic.Location;
        Assert.AreNotEqual(Location.None, location);
        Assert.AreEqual("wallet.de.xliff", location.GetLineSpan().Path);
        Assert.AreEqual(0, location.GetLineSpan().StartLinePosition.Line);
        Assert.AreEqual(0, location.GetLineSpan().StartLinePosition.Character);
    }

    [TestMethod]
    public void ADocumentWithADifferentSourceLanguageIsReportedAndExcludedRatherThanSilentlyFoldedIn()
    {
        //f-15: only the source-language table of valid[0] (the first document in path order) ever
        //got accessor properties; a second document's own srcLang units still landed in the internal
        //Languages dictionary with no accessor and no diagnostic - an inconsistent, silent partial
        //drop. The mismatched document must now be reported through VFX304 and excluded entirely:
        //no accessor, and none of its text lands in any generated table either.
        var files = new[]
        {
            ("a.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="en">
                  <file id="wallet"><unit id="Hello"><segment><source>Hello</source></segment></unit></file>
                </xliff>
                """),
            ("b.xliff", """
                <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="fr">
                  <file id="wallet"><unit id="Bonjour"><segment><source>Bonjour</source></segment></unit></file>
                </xliff>
                """)
        };

        GeneratorDriverRunResult result = RunGenerator(files, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Diagnostic diagnostic = result.Diagnostics[0];
        Assert.AreEqual(WellKnownGeneratorDiagnostics.SourceLanguageMismatch, diagnostic.Id);
        string message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("b.xliff", message, StringComparison.Ordinal);
        Assert.Contains("fr", message, StringComparison.Ordinal);
        Assert.Contains("a.xliff", message, StringComparison.Ordinal);
        Assert.Contains("en", message, StringComparison.Ordinal);

        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        Assert.Contains("public static string Hello", code, StringComparison.Ordinal);
        Assert.DoesNotContain("Bonjour", code, StringComparison.Ordinal);
    }

    [TestMethod]
    public void TheGeneratedSourceCompilesAndRunsUnderCSharp73()
    {
        //f-14: a netstandard2.0-targeting consumer with no explicit LangVersion defaults to C# 7.3.
        //The emitted class used to require C# 9 (target-typed `new`, nullable reference annotations,
        //the `is not null` pattern combinator), which fails at that language version with
        //CS8370-class errors - exactly the consumer scenario the generator, itself netstandard2.0,
        //is built to support. Parsing and compiling the generated source under
        //LanguageVersion.CSharp7_3 explicitly, then actually invoking an accessor, proves the
        //emitted code needs nothing newer.
        GeneratorDriverRunResult result = RunGenerator(TwoLanguageXliff, "Bootstrap73", TestContext.CancellationToken);
        Assert.HasCount(0, result.Diagnostics);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();

        var parseOptions = new CSharpParseOptions(LanguageVersion.CSharp7_3);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Bootstrap73",
            syntaxTrees: [CSharpSyntaxTree.ParseText(code, parseOptions, cancellationToken: TestContext.CancellationToken)],
            references: NetReferences(),
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        using var peStream = new MemoryStream();
        EmitResult emitResult = compilation.Emit(peStream, cancellationToken: TestContext.CancellationToken);
        Assert.IsTrue(emitResult.Success, string.Join(Environment.NewLine, emitResult.Diagnostics));

        peStream.Position = 0;
        var context = new AssemblyLoadContext("Bootstrap73", isCollectible: true);
        Assembly assembly = context.LoadFromStream(peStream);
        Type translationsType = assembly.GetType("Bootstrap73.Localization.Translations")
            ?? throw new InvalidOperationException("The generated assembly does not declare a Translations type.");

        //Resolve reads the real CurrentUICulture, so pin it to a culture unrelated to both "en"
        //(source) and "fi" (target) instead of trusting whatever the host machine's UI culture
        //happens to be, which would make this assertion pass or fail depending on where it runs.
        CultureInfo originalCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("de");
            Assert.AreEqual("Your credentials, on your terms.", GetAccessor(translationsType, "HomeHeadline"));
        }
        finally
        {
            CultureInfo.CurrentUICulture = originalCulture;
        }

        context.Unload();
    }

    [TestMethod]
    public void TheGeneratorAssemblyTargetsNetStandardTwoZero()
    {
        //r1-57: a generator must target netstandard2.0 to load into every compiler host,
        //including the in-process Visual Studio language service, which runs on .NET
        //Framework; targeting net10.0 loads only under the matching .NET SDK compiler.
        var targetFrameworkAttribute = typeof(XliffSourceGenerator).Assembly
            .GetCustomAttribute<System.Runtime.Versioning.TargetFrameworkAttribute>();

        Assert.IsNotNull(targetFrameworkAttribute);
        Assert.Contains(".NETStandard,Version=v2.0", targetFrameworkAttribute.FrameworkName, StringComparison.Ordinal);
    }

    [TestMethod]
    public void ADocumentInAForeignNamespaceIsRefusedEvenWithAnXliffLocalName()
    {
        //r1-69: an <xliff> element outside the XLIFF 2.x core namespace (here, no
        //namespace at all) is not XLIFF 2 per spec 4.1; matching on local name alone, as
        //the generator used to, would accept it and emit accessors for a document the
        //core reader would refuse outright.
        var result = RunGenerator("""
            <xliff version="2.0" srcLang="en">
              <file id="wallet">
                <unit id="A">
                  <segment>
                    <source>Text.</source>
                  </segment>
                </unit>
              </file>
            </xliff>
            """, "Bootstrap", TestContext.CancellationToken);

        Assert.HasCount(1, result.Diagnostics);
        Assert.AreEqual(WellKnownGeneratorDiagnostics.ParseFailure, result.Diagnostics[0].Id);
        Assert.Contains("XLIFF 2.x core namespace", result.Diagnostics[0].GetMessage(CultureInfo.InvariantCulture), StringComparison.Ordinal);
        Assert.HasCount(0, result.Results[0].GeneratedSources);
    }

    private static void AssertCachedOrUnchanged(
        ImmutableDictionary<string, ImmutableArray<IncrementalGeneratorRunStep>> trackedSteps,
        string stepName)
    {
        ImmutableArray<IncrementalGeneratorRunStep> steps = trackedSteps[stepName];
        Assert.HasCount(1, steps);
        foreach(var output in steps[0].Outputs)
        {
            Assert.IsTrue(
                output.Reason is IncrementalStepRunReason.Cached or IncrementalStepRunReason.Unchanged,
                $"Step '{stepName}' reported {output.Reason} instead of Cached or Unchanged.");
        }
    }

    private static string GetAccessor(Type translationsType, string propertyName)
    {
        PropertyInfo property = translationsType.GetProperty(propertyName, BindingFlags.Public | BindingFlags.Static)
            ?? throw new InvalidOperationException($"Translations does not declare a property named '{propertyName}'.");

        return (string)property.GetValue(null)!;
    }

    private static (Type TranslationsType, AssemblyLoadContext Context) EmitAndLoad(
        string xliffContent,
        string assemblyName,
        CancellationToken cancellationToken,
        int expectedDiagnosticCount = 0)
    {
        return EmitAndLoad(RunGenerator(xliffContent, assemblyName, cancellationToken), assemblyName, expectedDiagnosticCount, cancellationToken);
    }

    private static (Type TranslationsType, AssemblyLoadContext Context) EmitAndLoad(
        IEnumerable<(string Path, string Content)> files,
        string assemblyName,
        CancellationToken cancellationToken,
        int expectedDiagnosticCount = 0)
    {
        return EmitAndLoad(RunGenerator(files, assemblyName, cancellationToken), assemblyName, expectedDiagnosticCount, cancellationToken);
    }

    private static (Type TranslationsType, AssemblyLoadContext Context) EmitAndLoad(
        GeneratorDriverRunResult result,
        string assemblyName,
        int expectedDiagnosticCount,
        CancellationToken cancellationToken)
    {
        Assert.HasCount(expectedDiagnosticCount, result.Diagnostics);
        string code = result.Results[0].GeneratedSources[0].SourceText.ToString();
        var compilation = CSharpCompilation.Create(
            assemblyName: assemblyName,
            syntaxTrees: [CSharpSyntaxTree.ParseText(code, cancellationToken: cancellationToken)],
            references: NetReferences(),
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        using var peStream = new MemoryStream();
        EmitResult emitResult = compilation.Emit(peStream, cancellationToken: cancellationToken);
        Assert.IsTrue(emitResult.Success, string.Join(Environment.NewLine, emitResult.Diagnostics));

        peStream.Position = 0;
        var context = new AssemblyLoadContext(assemblyName, isCollectible: true);
        Assembly assembly = context.LoadFromStream(peStream);
        Type translationsType = assembly.GetType($"{assemblyName}.Localization.Translations")
            ?? throw new InvalidOperationException("The generated assembly does not declare a Translations type.");

        return (translationsType, context);
    }

    private static string Normalize(string text)
    {
        return text.Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static GeneratorDriverRunResult RunGenerator(string xliffContent, string assemblyName, CancellationToken cancellationToken)
    {
        return RunGenerator([("wallet.fi.xliff", xliffContent)], assemblyName, cancellationToken);
    }

    private static GeneratorDriverRunResult RunGenerator(IEnumerable<(string Path, string Content)> files, string assemblyName, CancellationToken cancellationToken)
    {
        var generator = new XliffSourceGenerator();
        var additionalTexts = files
            .Select(file => (AdditionalText)new MemoryAdditionalText(file.Path, file.Content))
            .ToArray();
        var driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: additionalTexts);
        var compilation = CSharpCompilation.Create(
            assemblyName: assemblyName,
            syntaxTrees: [],
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);

        //Kills the finding r-testquality-7 mutant: RunGenerators previously ran with no
        //cancellation token, so a hang inside generator execution would never be interrupted
        //by the test host's own timeout signal.
        return driver.RunGenerators(compilation, cancellationToken).GetRunResult();
    }

    private static List<MetadataReference> NetReferences()
    {
        string runtimeDirectory = global::System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory();

        return
        [
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Runtime.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Collections.dll")),
            MetadataReference.CreateFromFile(Path.Combine(runtimeDirectory, "System.Globalization.dll")),
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
        ];
    }

    /// <summary>
    /// An <see cref="AdditionalText"/> backed by an in-memory string, so a generator test can hand
    /// the driver XLIFF content without touching disk.
    /// </summary>
    private sealed class MemoryAdditionalText: AdditionalText
    {
        /// <summary>
        /// Initializes a new instance carrying <paramref name="content"/> at <paramref name="path"/>.
        /// </summary>
        /// <param name="path">The additional text's path, as the generator sees it.</param>
        /// <param name="content">The additional text's content.</param>
        public MemoryAdditionalText(string path, string content)
        {
            Path = path;
            Content = content;
        }

        /// <summary>The additional text's path, as the generator sees it.</summary>
        public override string Path { get; }

        /// <summary>The additional text's content.</summary>
        private string Content { get; }

        /// <summary>
        /// Returns <see cref="Content"/> as a <see cref="SourceText"/>.
        /// </summary>
        /// <param name="cancellationToken">Unused; building the source text has no async path to cancel.</param>
        /// <returns>The additional text's content as source text.</returns>
        public override SourceText GetText(CancellationToken cancellationToken = default)
        {
            return SourceText.From(Content, Encoding.UTF8);
        }
    }
}
